/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionepazienti;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Riccardo
 */
public class ElementiListaTerapie extends javax.swing.JPanel {
    private Terapy terapiaInfo;
    private Terapia parent;
    
    
    public ElementiListaTerapie(Terapia p,Terapy t) {
        initComponents();
        this.setVisible(true);
        terapiaInfo=t;
        parent=p;
        
        dataFine.setDate(t.getDataFine());
        dataInizio.setDate(t.getDataInizio());
        listaTerapie.setSelectedItem(t.getTerapia());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaTerapie = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dataInizio = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        dataFine = new org.jdesktop.swingx.JXDatePicker();
        elimina = new javax.swing.JButton();

        listaTerapie.setEditable(true);
        listaTerapie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listaTerapie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaTerapieActionPerformed(evt);
            }
        });

        jLabel2.setText("inizio:");

        dataInizio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataInizioActionPerformed(evt);
            }
        });

        jLabel3.setText("fine:");

        dataFine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataFineActionPerformed(evt);
            }
        });

        elimina.setText("X");
        elimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(listaTerapie, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dataInizio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataFine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(elimina, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(listaTerapie, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2)
                .addComponent(dataInizio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3)
                .addComponent(dataFine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(elimina))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dataInizioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataInizioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataInizioActionPerformed

    private void dataFineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataFineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataFineActionPerformed

    private void listaTerapieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaTerapieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaTerapieActionPerformed

    private void eliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaActionPerformed
        int reply = JOptionPane.showConfirmDialog(null,"Vuoi eliminare questo elemento?", "Conferma eliminazione", JOptionPane.YES_NO_OPTION);
        if(reply==JOptionPane.YES_OPTION)
        {  
            try {
                PreparedStatement st=GestioneDatabase.preparedStatement("DELETE FROM Paziente_Terapia WHERE Data_Inizio=? AND ID_Paziente=? AND Terapia=?");
                st.setDate(1, terapiaInfo.getDataInizio());
                st.setInt(2, terapiaInfo.getIdPaz());
                st.setString(3, terapiaInfo.getTerapia());
                st.executeUpdate();
                this.setEnabled(false);
                parent.aggiornaTerapie();
            } catch (SQLException ex) {
                Logger.getLogger(ElementiListaTerapie.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_eliminaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker dataFine;
    private org.jdesktop.swingx.JXDatePicker dataInizio;
    private javax.swing.JButton elimina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> listaTerapie;
    // End of variables declaration//GEN-END:variables
}
